# Generated by Django 3.1.7 on 2021-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='alert_type',
            field=models.CharField(choices=[('danger', 'Critical'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info')], max_length=10),
        ),
    ]
