# Generated by Django 3.1.7 on 2021-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20210327_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='monitor_time',
            field=models.IntegerField(null=True),
        ),
    ]
